DISTANCE = "DISTANCE"
GROUP = "GROUP"
UNIFORM = "UNIFORM"
NEIGHBORS = "NEIGHBORS"

DEFAULT_CELL_VISUAL_TYPE = DISTANCE

CELL_VISUAL_ENUM = (
    (DISTANCE, "Distance", ""),
    (GROUP, "Cell Group", ""),
    (UNIFORM, "Uniform", ""),
    (NEIGHBORS, "Neighbors Amount", ""),
)


VG_DISPLACE, VG_STAIRS, VG_THICKNESS, VG_LONGEST_PATH = (
    "MG_DISPLACE",
    "MG_STAIRS",
    "MG_CELL_THICKNESS",
    "MG_LONGEST_PATH",
)

VERTEX_GROUPS = VG_STAIRS, VG_THICKNESS, VG_LONGEST_PATH
