NORTH, SOUTH, WEST, EAST, UP, DOWN = 0, 2, 1, 3, 4, 5
TRI_UP_RIGHT, TRI_UP_LEFT, TRI_UP_DOWN = 0, 1, 2
TRI_DN_RIGHT, TRI_DN_LEFT, TRI_DN_UP = 1, 0, 2
HEX_NORTH_EAST, HEX_NORTH, HEX_NORTH_WEST, HEX_SOUTH_WEST, HEX_SOUTH, HEX_SOUTH_EAST = range(0, 6)
POL_CCW, POL_IN, POL_CW = 0, 1, 2

SQRT3_OVER2 = (3 ** 0.5) / 2
